/**
 * 0009 — AI marking assistance.
 *
 * The brief's exit criterion for this phase is one sentence: no AI writes a
 * grade unreviewed. That is a claim about the schema, not about prompt
 * wording, so this migration is what makes it true.
 *
 * A draft is a different KIND of object from a grade. It lives in its own
 * table, and there is no column here that any gradebook query reads. The only
 * way a suggestion becomes a mark is for a person to call gradeSubmission,
 * which has required a human actor since 0007. So "the AI graded my work" is
 * not a thing that can happen — a teacher graded it, possibly after reading a
 * suggestion, and grade_events records both facts separately.
 *
 * Keeping the draft after it is acted on is deliberate. It is the only way to
 * later answer whether teachers actually disagree with the model, which is the
 * question that decides whether this feature should exist at all. A tool that
 * is accepted unread is worse than no tool, and the evidence for that lives
 * here: the suggested score and the score that was finally recorded.
 */
export const sql = `
CREATE TABLE IF NOT EXISTS grade_drafts (
  id               text PRIMARY KEY,
  organization_id  text NOT NULL,
  submission_id    text NOT NULL,
  -- Which model produced this, recorded verbatim. When a teacher accepts, the
  -- same string is copied onto the grade event, so an appeal can be told not
  -- just that a model was involved but which one.
  model            text NOT NULL,
  -- What it suggested. Nullable score: a model is allowed to say it cannot
  -- responsibly put a number on something, and that is a better answer than
  -- an invented one.
  suggested_score  numeric(6,2),
  suggested_feedback text NOT NULL DEFAULT '',
  -- Why. Shown to the teacher, never to the student, and never copied into
  -- feedback automatically — it is the model's reasoning about a person, and
  -- the teacher is the one who decides what that person is told.
  rationale        text NOT NULL DEFAULT '',
  -- The model's own stated confidence, 0-1. Advisory only; nothing branches
  -- on it, because a confident wrong answer is the failure mode being
  -- guarded against and a threshold would automate exactly the wrong half.
  confidence       numeric(4,3),
  -- Who asked for it. A draft is never generated by a background job on
  -- nobody's behalf.
  requested_by     text REFERENCES users(id) ON DELETE SET NULL,
  -- pending | accepted | edited | rejected | stale
  status           text NOT NULL DEFAULT 'pending',
  -- What the teacher actually recorded, when they did. The pair of this and
  -- suggested_score is the whole point of keeping the row.
  resolved_score   numeric(6,2),
  resolved_by      text REFERENCES users(id) ON DELETE SET NULL,
  resolved_at      timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (organization_id, submission_id)
    REFERENCES assignment_submissions (organization_id, id) ON DELETE CASCADE,
  CONSTRAINT grade_drafts_status_known
    CHECK (status IN ('pending', 'accepted', 'edited', 'rejected', 'stale')),
  CONSTRAINT grade_drafts_confidence_range
    CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1))
);

-- The marking screen asks for the newest draft on one submission.
CREATE INDEX IF NOT EXISTS idx_grade_drafts_submission
  ON grade_drafts(submission_id, created_at DESC);

-- "How often is the model overridden" — the question that decides whether
-- this feature earns its place. Indexed so asking it stays cheap.
CREATE INDEX IF NOT EXISTS idx_grade_drafts_org_status
  ON grade_drafts(organization_id, status);
`;
